#!/usr/bin/env bash
#
# Mike Word Add-in — one-command local dev setup + launch.
#
#   bash word-addin/scripts/dev.sh
#
# What it does (idempotent — safe to re-run):
#   1. Verifies Node is available.
#   2. Reads the backend location and writes word-addin/.env with a same-origin
#      API route so the backend-managed HttpOnly session cookie works in Word.
#   3. Runs `npm install` to verify and repair the dependency tree.
#   4. Checks the Mike backend is reachable (warns if not).
#   5. Verifies port 3200 is free for the dev server and manifest.
#   6. Installs the trusted dev HTTPS certificate if Word doesn't already trust
#      it (this step may prompt for your keychain/admin password).
#   7. Runs `npm start`; webpack loads `.env` and boots its dev server on
#      https://localhost:3200. It sideloads into Word unless
#      WORD_ADDIN_SIDELOAD=0.
#
# Prerequisite: the Mike API must be running (`npm run dev` in backend/),
# and its database and GoTrue settings must be filled in (see the repo README).
#
# Pass --setup-only to do everything except the port check + final `npm start`.
#
set -euo pipefail

SETUP_ONLY=0
[ "${1:-}" = "--setup-only" ] && SETUP_ONLY=1

cd "$(dirname "$0")/.."          # -> word-addin
ADDIN_DIR="$(pwd)"

step() { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
ok()   { printf "    \033[1;32m✔\033[0m %s\n" "$1"; }
warn() { printf "    \033[1;33m! %s\033[0m\n" "$1"; }

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
step "Checking prerequisites"
command -v node >/dev/null 2>&1 || { echo "Node.js 22+ is required (https://nodejs.org)"; exit 1; }
NODE_MAJOR="$(node --version | sed -E 's/^v([0-9]+).*/\1/')"
[ "$NODE_MAJOR" -ge 22 ] || { echo "Node.js 22+ is required; found $(node --version)"; exit 1; }
ok "node $(node --version)"

# ── 2. Read the shared backend location ──────────────────────────────────────
step "Reading backend config"
read_env_file() { [ -f "$1" ] && grep -E "^$2=" "$1" | head -1 | cut -d= -f2- | tr -d '"' || true; }
read_addin_env() { read_env_file .env "$1"; }

API_TARGET="${API_PROXY_TARGET:-$(read_addin_env API_PROXY_TARGET)}"
API_TARGET="${API_TARGET:-http://localhost:3001}"
SIDELOAD_SETTING="${WORD_ADDIN_SIDELOAD:-$(read_addin_env WORD_ADDIN_SIDELOAD)}"
SIDELOAD_SETTING="${SIDELOAD_SETTING:-1}"
# ── 3. Write .env ─────────────────────────────────────────────────────────────
# The add-in is served over HTTPS (Word requires it). The local backend is HTTP,
# which Word's WebView blocks as mixed content, so the bundle points at
# SAME-ORIGIN HTTPS paths on the dev server, which proxies them to the real
# backend (see the proxy config in webpack.config.js). Authentication and API
# traffic share this route so the browser only receives HttpOnly cookies.
step "Configuring .env (proxied through the HTTPS dev server)"
DEV_ORIGIN="https://localhost:3200"
# Preserve an explicit override; otherwise link account settings to the
# deployed Mike app.
WEB_APP_URL="${REACT_APP_WEB_APP_URL:-$(read_addin_env REACT_APP_WEB_APP_URL)}"
WEB_APP_URL="${WEB_APP_URL:-https://app.mikeoss.com}"
cat > .env <<EOF
# Generated by scripts/dev.sh. URLs point at the dev server's HTTPS proxy
# (webpack.config.js) so the task pane never makes blocked HTTP / cross-origin
# requests. The real backend is reached via API_PROXY_TARGET.
REACT_APP_API_BASE_URL=${DEV_ORIGIN}/api
REACT_APP_WEB_APP_URL=${WEB_APP_URL}
WORD_ADDIN_SIDELOAD=${SIDELOAD_SETTING}
API_PROXY_TARGET=${API_TARGET}
EOF
ok "wrote the same-origin API route"

# ── 4. Dependencies ──────────────────────────────────────────────────────────
step "Installing dependencies"
npm install
ok "dependencies installed and verified"

# ── 5. Mike backend health ───────────────────────────────────────────────────
# The backend owns sign-in, session refresh, chat, actions, workflows, project
# browsing, and uploads. The add-in never contacts GoTrue directly.
step "Checking the Mike backend is running"
BACKEND_OK=1

# 5a. Mike backend — GET /health returns {"ok":true}.
health_code="$(curl -s -m6 -o /dev/null -w '%{http_code}' "$API_TARGET/health" 2>/dev/null)" || true
[ -n "$health_code" ] || health_code=000
if [ "$health_code" = "200" ]; then
    ok "Mike backend healthy at $API_TARGET"
else
    BACKEND_OK=0
    warn "Mike API NOT reachable at $API_TARGET (HTTP $health_code)."
    warn "Start it:  cd backend && npm run dev"
fi

# ── 6. Port 3200 availability ─────────────────────────────────────────────────
# The webpack dev server AND the add-in manifest are hardwired to
# https://localhost:3200. Fail fast with a clear message BEFORE the cert prompt /
# launch — otherwise `npm start` dies with an opaque EADDRINUSE.
# (Skipped for --setup-only, which never launches; re-running while the add-in's
# own server is already up correctly trips this too.)
if [ "$SETUP_ONLY" != 1 ]; then
    step "Checking port 3200 is free"
    if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:3200 -sTCP:LISTEN >/dev/null 2>&1; then
        holder="$(lsof -nP -iTCP:3200 -sTCP:LISTEN 2>/dev/null | awk 'NR==2{print $1" (pid "$2")"}')"
        warn "Port 3200 is already in use by: ${holder:-another process}"
        echo "    The add-in dev server and Word's manifest both require https://localhost:3200."
        echo "    Stop the process using it first:"
        echo "      lsof -nP -iTCP:3200 -sTCP:LISTEN     # confirm what it is"
        echo "    Then re-run this script."
        exit 1
    fi
    ok "port 3200 is free"
fi

# ── 7. Dev HTTPS certificate ─────────────────────────────────────────────────
# office-addin-dev-certs regenerates the certificate (AND a new signing CA)
# whenever the old one expires (~30 days) — the webpack dev server triggers
# this silently on startup. The tool's own `verify` only checks that a CA *by
# that name* exists in the trust store, so after a regeneration it reports
# "trusted" while the OS actually trusts the OLD CA — and Word rejects the
# pane with "content is blocked because it isn't signed by a valid security
# certificate". Verify the ACTUAL chain against the OS trust store instead,
# and force a real reinstall when it has drifted.
step "Checking dev HTTPS certificate"
CERT_DIR="$HOME/.office-addin-dev-certs"
cert_trusted() {
    [ -f "$CERT_DIR/localhost.crt" ] || return 1
    if [ "$(uname)" = "Darwin" ]; then
        # Ground truth: does macOS trust this exact leaf for SSL on localhost?
        security verify-cert -c "$CERT_DIR/localhost.crt" -p ssl -s localhost >/dev/null 2>&1
    else
        npx --no-install office-addin-dev-certs verify >/dev/null 2>&1
    fi
}
if cert_trusted; then
    ok "dev certificate trusted (verified against the OS trust store)"
else
    warn "Dev certificate is missing, expired, or signed by a CA the OS no longer trusts."
    warn "Reinstalling — this may prompt for your keychain/admin password…"
    # `install` skips itself when its name-based verify passes — which is
    # exactly the drift case — so uninstall first to force a real install.
    npx office-addin-dev-certs uninstall >/dev/null 2>&1 || true
    npx office-addin-dev-certs install || true
    if ! cert_trusted && [ "$(uname)" = "Darwin" ] && [ -f "$CERT_DIR/ca.crt" ]; then
        # Last resort: trust the current CA directly.
        warn "Trusting the current dev CA directly (keychain prompt)…"
        security add-trusted-cert -r trustRoot \
            -k "$HOME/Library/Keychains/login.keychain-db" "$CERT_DIR/ca.crt" || true
    fi
    if cert_trusted; then
        warn "Cert trusted — fully QUIT Word (Cmd-Q) before launching so it reloads trust."
    else
        warn "Certificate STILL not trusted — Word will refuse the pane."
        warn "See docs/word-addin-development.md → Word reports an invalid development certificate."
        exit 1
    fi
fi

# ── 8. Launch ────────────────────────────────────────────────────────────────
if [ "$SETUP_ONLY" = 1 ]; then
    step "Setup complete"
    [ "$BACKEND_OK" = 1 ] || warn "Backend is not fully up — start Mike before launching (see above)."
    echo "    To launch: cd $ADDIN_DIR && npm start"
    exit 0
fi

if [ "$BACKEND_OK" != 1 ]; then
    step "Mike backend is not running"
    echo "    The add-in needs Mike running before it does anything useful. Start it:"
    echo "      (backend/)    npm run dev        # the Mike API on :3001"
    echo "    and make sure backend/.env contains the database and GoTrue settings."
    echo "    Then re-run this script. To launch anyway, set FORCE=1 (sign-in will fail until Mike is up)."
    [ "${FORCE:-0}" = 1 ] || exit 1
    warn "FORCE=1 set — launching despite the backend being down."
fi

case "$SIDELOAD_SETTING" in
0|false|FALSE|False|no|NO|No|off|OFF|Off)
    step "Starting dev server without opening Word"
    echo "    WORD_ADDIN_SIDELOAD=${SIDELOAD_SETTING}; webpack will serve the task pane only."
    ;;
*)
    step "Starting dev server + sideloading into Word"
    echo "    (webpack serves https://localhost:3200 and proxies /api to the"
    echo "     Mike backend; Word opens with the add-in.)"
    echo "    In Word: Home → Mike Legal AI → Mike"
    ;;
esac
exec npm start
